## Transform Data - Cleaning the cities_df and save into new df called cities_df_cleaned

In [8]:
from api_project.ETL.transform_data import TransformData

transform_data = TransformData()
df = transform_data.load_reports_df("reports_USA_2020-04-16")
df.head()

2026-04-30 12:33:12,205 | INFO | Loading raw API JSON from C:\Users\rafae\PycharmProjects\Data_Pipelines\api_project\raw_data\covid_api.json

,date,confirmed,deaths,recovered,confirmed_diff,deaths_diff,recovered_diff,last_update,active,active_diff,fatality_rate,iso,region_name,province,region_lat,region_long,region_cities
0,2020-04-16,11057,579,0,115,27,0,2020-04-16 23:30:51,10478,88,0.0524,USA,US,Washington,47.4009,-121.4905,"[{'name': 'Adams', 'date': '2020-04-16', 'fips..."
1,2020-04-16,25734,1072,0,1141,123,0,2020-04-16 23:30:51,24662,1018,0.0417,USA,US,Illinois,40.3495,-88.9861,"[{'name': 'Adams', 'date': '2020-04-16', 'fips..."
2,2020-04-16,27677,956,0,991,96,0,2020-04-16 23:30:51,26721,895,0.0345,USA,US,California,36.1162,-119.6816,"[{'name': 'Alameda', 'date': '2020-04-16', 'fi..."
3,2020-04-16,4237,150,0,273,8,0,2020-04-16 23:30:51,4087,265,0.0354,USA,US,Arizona,33.7298,-111.4312,"[{'name': 'Apache', 'date': '2020-04-16', 'fip..."
4,2020-04-16,223691,14832,0,9237,3215,0,2020-04-16 23:30:51,208859,6022,0.0663,USA,US,New York,42.1657,-74.9481,"[{'name': 'Albany', 'date': '2020-04-16', 'fip..."

In [9]:
df.columns

Index(['date', 'confirmed', 'deaths', 'recovered', 'confirmed_diff',
       'deaths_diff', 'recovered_diff', 'last_update', 'active', 'active_diff',
       'fatality_rate', 'iso', 'region_name', 'province', 'region_lat',
       'region_long', 'region_cities'],
      dtype='str')

In [16]:
df["region_cities"].iloc[0]

[{'name': 'Adams',
  'date': '2020-04-16',
  'fips': 53001,
  'lat': '46.98299757',
  'long': '-118.56017340000001',
  'confirmed': 40,
  'deaths': 0,
  'confirmed_diff': 1,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Asotin',
  'date': '2020-04-16',
  'fips': 53003,
  'lat': '46.18894415',
  'long': '-117.2022851',
  'confirmed': 10,
  'deaths': 0,
  'confirmed_diff': 4,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Benton',
  'date': '2020-04-16',
  'fips': 53005,
  'lat': '46.23946995',
  'long': '-119.51208340000001',
  'confirmed': 283,
  'deaths': 34,
  'confirmed_diff': 17,
  'deaths_diff': 5,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Chelan',
  'date': '2020-04-16',
  'fips': 53007,
  'lat': '47.87046092',
  'long': '-120.6173956',
  'confirmed': 63,
  'deaths': 5,
  'confirmed_diff': 2,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Clallam',
  'date': '2020-04-16',
  'fips': 53009,
  'lat': '48.04754642',
  'long': '-123.92263190000001',
  'confirmed': 14,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Clark',
  'date': '2020-04-16',
  'fips': 53011,
  'lat': '45.77568046',
  'long': '-122.48292040000001',
  'confirmed': 265,
  'deaths': 15,
  'confirmed_diff': 7,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Columbia',
  'date': '2020-04-16',
  'fips': 53013,
  'lat': '46.29442881',
  'long': '-117.9051983',
  'confirmed': 1,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Cowlitz',
  'date': '2020-04-16',
  'fips': 53015,
  'lat': '46.19074721',
  'long': '-122.6782231',
  'confirmed': 26,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Douglas',
  'date': '2020-04-16',
  'fips': 53017,
  'lat': '47.7361335',
  'long': '-119.69293700000001',
  'confirmed': 34,
  'deaths': 1,
  'confirmed_diff': 5,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Ferry',
  'date': '2020-04-16',
  'fips': 53019,
  'lat': '48.471143100000006',
  'long': '-118.5154041',
  'confirmed': 1,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Franklin',
  'date': '2020-04-16',
  'fips': 53021,
  'lat': '46.53351425',
  'long': '-118.9018212',
  'confirmed': 152,
  'deaths': 4,
  'confirmed_diff': -33,
  'deaths_diff': 2,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Grant',
  'date': '2020-04-16',
  'fips': 53025,
  'lat': '47.20753737',
  'long': '-119.4500749',
  'confirmed': 129,
  'deaths': 2,
  'confirmed_diff': 7,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Grays Harbor',
  'date': '2020-04-16',
  'fips': 53027,
  'lat': '47.14003705',
  'long': '-123.7820567',
  'confirmed': 12,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Island',
  'date': '2020-04-16',
  'fips': 53029,
  'lat': '48.14713305',
  'long': '-122.5216407',
  'confirmed': 164,
  'deaths': 8,
  'confirmed_diff': 1,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Jefferson',
  'date': '2020-04-16',
  'fips': 53031,
  'lat': '47.75003077',
  'long': '-123.56097040000002',
  'confirmed': 28,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'King',
  'date': '2020-04-16',
  'fips': 53033,
  'lat': '47.49137892',
  'long': '-121.8346131',
  'confirmed': 4697,
  'deaths': 312,
  'confirmed_diff': 77,
  'deaths_diff': 9,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Kitsap',
  'date': '2020-04-16',
  'fips': 53035,
  'lat': '47.63479026',
  'long': '-122.6436061',
  'confirmed': 132,
  'deaths': 1,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Kittitas',
  'date': '2020-04-16',
  'fips': 53037,
  'lat': '47.12521214',
  'long': '-120.67943899999999',
  'confirmed': 14,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Klickitat',
  'date': '2020-04-16',
  'fips': 53039,
  'lat': '45.87325839',
  'long': '-120.7913598',
  'confirmed': 16,
  'deaths': 2,
  'confirmed_diff': 1,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Lewis',
  'date': '2020-04-16',
  'fips': 53041,
  'lat': '46.57756476',
  'long': '-122.39257690000001',
  'confirmed': 19,
  'deaths': 2,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Lincoln',
  'date': '2020-04-16',
  'fips': 53043,
  'lat': '47.57705241',
  'long': '-118.41943880000001',
  'confirmed': 2,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Mason',
  'date': '2020-04-16',
  'fips': 53045,
  'lat': '47.35007586',
  'long': '-123.1863685',
  'confirmed': 20,
  'deaths': 0,
  'confirmed_diff': 1,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Okanogan',
  'date': '2020-04-16',
  'fips': 53047,
  'lat': '48.54855019',
  'long': '-119.73872240000001',
  'confirmed': 15,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Pacific',
  'date': '2020-04-16',
  'fips': 53049,
  'lat': '46.55418369',
  'long': '-123.7285716',
  'confirmed': 1,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Pend Oreille',
  'date': '2020-04-16',
  'fips': 53051,
  'lat': '48.53234021',
  'long': '-117.2741804',
  'confirmed': 1,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Pierce',
  'date': '2020-04-16',
  'fips': 53053,
  'lat': '47.03892768',
  'long': '-122.14059579999999',
  'confirmed': 1022,
  'deaths': 28,
  'confirmed_diff': 22,
  'deaths_diff': 5,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'San Juan',
  'date': '2020-04-16',
  'fips': 53055,
  'lat': '48.60182783',
  'long': '-122.96745',
  'confirmed': 13,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Skagit',
  'date': '2020-04-16',
  'fips': 53057,
  'lat': '48.48171488',
  'long': '-121.766131',
  'confirmed': 209,
  'deaths': 6,
  'confirmed_diff': 11,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Skamania',
  'date': '2020-04-16',
  'fips': 53059,
  'lat': '46.02408726',
  'long': '-121.91644029999999',
  'confirmed': 3,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Snohomish',
  'date': '2020-04-16',
  'fips': 53061,
  'lat': '48.04615983',
  'long': '-121.7170703',
  'confirmed': 2032,
  'deaths': 86,
  'confirmed_diff': 44,
  'deaths_diff': 6,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Spokane',
  'date': '2020-04-16',
  'fips': 53063,
  'lat': '47.62113146',
  'long': '-117.4046494',
  'confirmed': 286,
  'deaths': 17,
  'confirmed_diff': 8,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Stevens',
  'date': '2020-04-16',
  'fips': 53065,
  'lat': '48.40035475',
  'long': '-117.8542701',
  'confirmed': 7,
  'deaths': 1,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Thurston',
  'date': '2020-04-16',
  'fips': 53067,
  'lat': '46.9291895',
  'long': '-122.82906559999999',
  'confirmed': 86,
  'deaths': 1,
  'confirmed_diff': 4,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Unassigned',
  'date': '2020-04-16',
  'fips': 90053,
  'lat': None,
  'long': None,
  'confirmed': 272,
  'deaths': 0,
  'confirmed_diff': -111,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Wahkiakum',
  'date': '2020-04-16',
  'fips': 53069,
  'lat': '46.29180039999999',
  'long': '-123.4250831',
  'confirmed': 2,
  'deaths': 0,
  'confirmed_diff': 0,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Walla Walla',
  'date': '2020-04-16',
  'fips': 53071,
  'lat': '46.23040051',
  'long': '-118.4775539',
  'confirmed': 26,
  'deaths': 0,
  'confirmed_diff': 3,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Whatcom',
  'date': '2020-04-16',
  'fips': 53073,
  'lat': '48.82227976',
  'long': '-121.74900179999999',
  'confirmed': 273,
  'deaths': 25,
  'confirmed_diff': 4,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Whitman',
  'date': '2020-04-16',
  'fips': 53075,
  'lat': '46.90022523',
  'long': '-117.52417630000001',
  'confirmed': 13,
  'deaths': 0,
  'confirmed_diff': 1,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'},
 {'name': 'Yakima',
  'date': '2020-04-16',
  'fips': 53077,
  'lat': '46.45738486',
  'long': '-120.73801259999999',
  'confirmed': 674,
  'deaths': 29,
  'confirmed_diff': 39,
  'deaths_diff': 0,
  'last_update': '2020-04-16 23:30:51'}]

In [34]:
import pandas as pd

base_cols = ["iso", "region_name", "province", "date"]  # keep what you need
cities_col = "region_cities"  # dict of persons data

cities_df = df[base_cols + [cities_col]].explode(cities_col, ignore_index=True)

# drop rows where the list was empty
cities_df = cities_df.dropna(subset=[cities_col])

# expand each city dict into columns
city_details = pd.json_normalize(cities_df[cities_col])
if "date" in city_details.columns:
    city_details = city_details.rename(columns={"date": "city_date"})

cities_df = pd.concat([cities_df.drop(columns=[cities_col]), city_details], axis=1)

# remove duplicate columns
cities_df_cleaned = cities_df.drop(columns=["region_name", "city_date", "last_update" ])

#rename column
cities_df_cleaned = cities_df_cleaned.rename(columns={"iso": "country"})
cities_df_cleaned

,country,province,date,name,fips,lat,long,confirmed,deaths,confirmed_diff,deaths_diff
0,USA,Washington,2020-04-16,Adams,53001.0,46.98299757,-118.56017340000001,40,0,1,0
1,USA,Washington,2020-04-16,Asotin,53003.0,46.18894415,-117.2022851,10,0,4,0
2,USA,Washington,2020-04-16,Benton,53005.0,46.23946995,-119.51208340000001,283,34,17,5
3,USA,Washington,2020-04-16,Chelan,53007.0,47.87046092,-120.6173956,63,5,2,0
4,USA,Washington,2020-04-16,Clallam,53009.0,48.04754642,-123.92263190000001,14,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2629,USA,South Dakota,2020-04-16,Turner,46125.0,43.3109081,-97.14865776,5,0,0,0
2630,USA,South Dakota,2020-04-16,Unassigned,90046.0,NaN,NaN,0,0,0,0
2631,USA,South Dakota,2020-04-16,Union,46127.0,42.83112163,-96.6557828,4,0,0,0
2632,USA,South Dakota,2020-04-16,Walworth,46129.0,45.43019636,-100.03075140000001,5,0,0,0
2633,USA,South Dakota,2020-04-16,Yankton,46135.0,43.00924485,-97.39467635,23,0,1,0

In [36]:
# save the cities_df_cleaned to a csv file
transform_data.save_df(cities_df_cleaned, "cities_df_cleaned.csv")

2026-04-30 13:07:59,075 | INFO | Saving DataFrame to C:\Users\rafae\PycharmProjects\Data_Pipelines\api_project\processed_data\cities_df_cleaned.csv

WindowsPath('C:/Users/rafae/PycharmProjects/Data_Pipelines/api_project/processed_data/cities_df_cleaned.csv')

In [37]:
cities_df_cleaned.columns

Index(['country', 'province', 'date', 'name', 'fips', 'lat', 'long',
       'confirmed', 'deaths', 'confirmed_diff', 'deaths_diff'],
      dtype='str')